#!/usr/bin/env python3
"""Regenerates core/src/world.rs from Natural Earth's coastline.

The map both interfaces draw is not a dependency and not a download: it is a
table in this repository, generated once by this script and committed. That is
deliberate. A night light that reaches the network to find out where the
coastlines are has the same defect as one that reaches the network to find out
where you are, and the second is the whole reason this project exists.

Source: Natural Earth 1:110m physical coastline, public domain.
  https://github.com/nvkelso/natural-earth-vector (geojson/ne_110m_coastline.geojson)
Natural Earth asks for no attribution and imposes no conditions; the credit
below is manners, not licence.

To refresh:
    curl -sSLO https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_coastline.geojson
    python3 tools/world.py ne_110m_coastline.geojson > core/src/world.rs
    cargo fmt
"""

import json
import sys

# Two decimal places is a hundredth of a degree, about a kilometre. The source
# is a 1:110 million map and the target is a few hundred pixels wide, so the
# digits past this describe a coastline neither one can draw.
PLACES = 2

HEADER = '''//! The world's coastlines, as polylines of (longitude, latitude) degrees.
//!
//! Generated by `tools/world.py` from Natural Earth's 1:110m physical
//! coastline, which is in the public domain. It lives here, in the crate that
//! depends on nothing, because both interfaces draw it and neither owns it —
//! and because the alternative was fetching it at runtime, which is precisely
//! the defect this project was written to answer.
//!
//! Do not edit by hand. Run the script.

/// Every coastline as its own run of points, longitude first. Separate runs
/// rather than one flat list because they are strokes, not a scatter: joining
/// the end of Iceland to the start of Africa would draw a line across the
/// Atlantic.
pub static COASTLINE: &[&[(f32, f32)]] = &[
'''

FOOTER = '''];

#[cfg(test)]
mod tests {
    use super::*;

    /// The table is generated, so the test is about the shape of it rather
    /// than its contents: enough coastline to read as a world, every point a
    /// real coordinate, and no run so short it draws nothing.
    #[test]
    fn the_coastline_is_a_plausible_world() {
        assert!(COASTLINE.len() > 50, "too few coastlines to be a world");
        let points: usize = COASTLINE.iter().map(|run| run.len()).sum();
        assert!(points > 3000, "only {points} points");
        for run in COASTLINE {
            assert!(run.len() >= 2, "a run of one point is not a line");
            for &(longitude, latitude) in run.iter() {
                assert!((-180.0..=180.0).contains(&longitude), "{longitude}");
                assert!((-90.0..=90.0).contains(&latitude), "{latitude}");
            }
        }
    }

    /// A cheap sanity check that the projection everyone draws with will put
    /// things where they belong: somewhere on the equator in the Atlantic
    /// there is no land, and Greenland is where Greenland is.
    #[test]
    fn the_far_north_is_populated_with_coastline() {
        let arctic = COASTLINE
            .iter()
            .flat_map(|run| run.iter())
            .filter(|(_, latitude)| *latitude > 60.0)
            .count();
        assert!(arctic > 100, "the northern coasts are missing");
    }
}
'''


def main() -> None:
    with open(sys.argv[1], encoding="utf-8") as handle:
        data = json.load(handle)

    sys.stdout.write(HEADER)
    for feature in data["features"]:
        geometry = feature["geometry"]
        if geometry["type"] != "LineString":
            continue
        run = [
            (round(lon, PLACES), round(lat, PLACES))
            for lon, lat in geometry["coordinates"]
        ]
        # Consecutive duplicates survive the rounding and draw nothing.
        deduped = [point for i, point in enumerate(run) if i == 0 or point != run[i - 1]]
        if len(deduped) < 2:
            continue
        body = ",".join(f"({lon:.2f},{lat:.2f})" for lon, lat in deduped)
        sys.stdout.write(f"    &[{body}],\n")
    sys.stdout.write(FOOTER)


if __name__ == "__main__":
    main()
